name: Create Release

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:              
    - uses: actions/checkout@v3

    - name: Create Release                
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}                          
      with:
        # tag_name: "v10"                               
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.sha }}
        # commit_sha: ${{ github.sha }}
        draft: false
        prerelease: false

    # - name: Upload Release Asset I
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./com.zionhuang.music_19.apk
    #     asset_name: com.zionhuang.music_19.apk
    #     asset_content_type: application/zip

    # - name: Upload Release Asset II
    #   uses: actions/upload-release-asset@v1
    #   # if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: Duolingo_5.144.3_Beta_Unlocked_universal.apk
    #       # AeroInsta_V24.0.0_Clone_DEFAULT__aeromods.app__.apk
        
    - name: Upload Release Asset II
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./AeroInsta_V24.0.0_Clone_DEFAULT__aeromods.app__.apk
        asset_name: AeroInsta_V24.0.0_Clone_DEFAULT__aeromods.app__.apk
        asset_content_type: application/zip

    # - name: Upload Release Asset III
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./Duolingo_5.144.3_Beta_Unlocked_universal.apk
    #     asset_name: Duolingo_5.144.3_Beta_Unlocked_universal.apk
    #     asset_content_type: application/zip

    # - name: Upload Release Asset IV
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./Adguard-4.4.65-Nightly-Mod-www.ReXdl.com.apk
    #     asset_name: Adguard-4.4.65-Nightly-Mod-www.ReXdl.com.apk
    #     asset_content_type: application/zip

        
